name: Build Docker image

on:
  push:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build --tag excalidraw:latest .

      - name: slim
        run: |
          curl -L -o ds.tar.gz https://github.com/slimtoolkit/slim/releases/download/1.40.11/dist_linux.tar.gz
          tar -xvf ds.tar.gz
          mv  dist_linux/slim /usr/local/bin/
          mv  dist_linux/slim-sensor /usr/local/bin/
          docker images
          slim build excalidraw:latest
          docker images